services:
  - type: web
    name: coda
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CODA_ADMIN_EMAIL
        sync: false
      - key: CSRF_SECRET
        generateValue: true
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
