// Subscription + reporting routes
const express = require('express');
const router = express.Router();
const sub = require('../modules/subscription');
const reporting = require('../modules/reporting');
const accounting = require('../modules/accounting');
const { requireAuth, requireBusiness } = require('../auth');
const { toCSV } = require('../utils');
const PDFDocument = require('pdfkit');

router.get('/tiers', (req, res) => res.json({ tiers: sub.listTiers() }));

router.use(requireAuth, requireBusiness);

router.get('/me', (req, res) => res.json({ subscription: sub.getSubscription(req.businessId) }));
router.post('/', (req, res) => res.status(201).json({ subscription: sub.createSubscription(req.businessId, req.body.tier) }));
router.post('/upgrade', (req, res) => res.json({ subscription: sub.upgradeSubscription(req.businessId, req.body.tier) }));
router.get('/payments', (req, res) => res.json({ payments: sub.listPayments(req.businessId, { limit: Number(req.query.limit) || 50 }) }));

// Dashboard aggregate
router.get('/dashboard', (req, res) => res.json({ dashboard: reporting.dashboard(req.businessId) }));

// Financial summary
router.get('/financial-summary', (req, res) => res.json({ summary: reporting.financialSummary(req.businessId) }));

// Exports — real CSV / PDF
router.get('/exports/financial.csv', (req, res) => {
  const csv = reporting.exportFinancialCSV(req.businessId, { from: req.query.from, to: req.query.to });
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="financial-${Date.now()}.csv"`);
  res.send(csv);
});

router.get('/exports/balance-sheet.csv', (req, res) => {
  const csv = reporting.exportBalanceSheetCSV(req.businessId, req.query.asOf);
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="balance-sheet-${Date.now()}.csv"`);
  res.send(csv);
});

router.get('/exports/ledger.csv', (req, res) => {
  const txs = accounting.listTransactions(req.businessId, { limit: 1000 });
  const rows = [];
  txs.forEach(t => {
    (t.lines || []).forEach(l => {
      rows.push({
        date: t.date,
        description: t.description,
        reference: t.reference,
        account: l.account || l.account_code || '',
        debit: l.debit || 0,
        credit: l.credit || 0
      });
    });
  });
  const csv = toCSV(rows, [
    { label: 'Date', value: r => r.date },
    { label: 'Description', value: r => r.description },
    { label: 'Reference', value: r => r.reference },
    { label: 'Account Code', value: r => r.account },
    { label: 'Debit (NGN)', value: r => Number(r.debit).toFixed(2) },
    { label: 'Credit (NGN)', value: r => Number(r.credit).toFixed(2) }
  ]);
  res.setHeader('Content-Type', 'text/csv; charset=utf-8');
  res.setHeader('Content-Disposition', `attachment; filename="general-ledger-${Date.now()}.csv"`);
  res.send(csv);
});


router.get('/exports/financial.pdf', async (req, res) => {
  try {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="financial-${Date.now()}.pdf"`);
    doc.pipe(res);
    doc.fontSize(20).text('Coda Financial Report', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('#666').text(new Date().toLocaleString('en-NG'), { align: 'center' });
    doc.moveDown(2);
    const pl = accounting.incomeStatement(req.businessId, { from: req.query.from, to: req.query.to });
    doc.fillColor('#000').fontSize(14).text('Profit & Loss');
    doc.moveDown(0.5);
    doc.fontSize(12);
    const lines = [
      ['Revenue', pl.revenue],
      ['Cost of Goods Sold', pl.costOfGoodsSold],
      ['Gross Profit', pl.grossProfit],
      ['Operating Expenses', pl.operatingExpenses],
      ['Net Profit', pl.netProfit],
    ];
    for (const [label, val] of lines) {
      doc.text(`${label.padEnd(30, ' ')}  NGN ${Number(val).toLocaleString('en-NG', { minimumFractionDigits: 2 })}`);
    }
    doc.moveDown(2);
    doc.fontSize(10).fillColor('#888').text('Generated by Coda ERP — compliant with Nigerian GAAP.', { align: 'center' });
    doc.end();
  } catch (err) {
    console.error('PDF generation error:', err);
    if (!res.headersSent) {
      res.status(500).json({ error: 'Failed to generate PDF' });
    }
  }
});

module.exports = router;
